from enum import Enum
#use 'pip install enum34'

class Games(Enum):
    Action = "action"
    Adventure = "adventure"
    Arcade = "arcade"
    Board = "board"
    Casual = "casual"
    Educational = "educational"
    Family = "family"
    Music = "music"
    Puzzle = "puzzle"
    Racing = "racing"
    RolePlaying = "role-playing"
    Simulation = "simulation"
    Sports = "sports-game"
    Strategy = "strategy"
    Trivia = "trivia"
    Word = "word"

class APPS(Enum):
    Books = "books-reference"
    Business = "busines"
    Comics = "comics"
    Communication = "communication"
    Education = "education"
    Entertainment = "entertainment"
    Finance = "finance"
    Health = "health-fitness"
    Libraries = "libraries-demo"
    LifeStyle = "lifestyle"
    LiveWallpaper = "live-wallpaper"
    Media = "media-video"
    Medical = "medical"
    Music = "music-audio"
    News = "news-magazines"
    Personalization = "personalization"
    Photography = "photography"
    Productivity = "productivity"
    Religious = "religious"
    Shopping = "shopping"
    Social = "social"
    Sport = "sports"
    Tools = "tools"
    Transportation = "transportation"
    Travel = "travel-local"
    Weather = "weather"
    Widgets = "widgets"
 
