import sqlite3
conn = sqlite3.connect('database.db')
conn.execute('''CREATE TABLE APPS
    (ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME CHAR(50) NOT NULL,
    PRICE INT NOT NULL,
    PAKAGE CHAR(75) NOT NULL,
    CATEGORY CHAR(25) NOT NULL,
    SUBMITTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )''')
